~/workspace$ python "start_ngrok.py"
                                                                                                                                                ERROR:  authentication failed: Usage of ngrok requires a verified account and authtoken.
ERROR:  
ERROR:  Sign up for an account: https://dashboard.ngrok.com/signup
ERROR:  Install your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken
ERROR:  
ERROR:  ERR_NGROK_4018
ERROR:  https://ngrok.com/docs/errors/err_ngrok_4018
ERROR:  
t=2025-02-13T15:28:23+0000 lvl=eror msg="failed to reconnect session" obj=tunnels.session err="authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
t=2025-02-13T15:28:23+0000 lvl=eror msg="session closing" obj=tunnels.session err="authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
t=2025-02-13T15:28:23+0000 lvl=eror msg="terminating with error" obj=app err="authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
t=2025-02-13T15:28:23+0000 lvl=crit msg="command failed" err="authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"
Traceback (most recent call last):
  File "/home/runner/workspace/start_ngrok.py", line 11, in <module>
    url = ngrok.connect(5000)
          ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ipfp4nb6nsp87msx9v5n8l5mir15qcy4-python3.12-pyngrok-7.1.6/lib/python3.12/site-packages/pyngrok/ngrok.py", line 316, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ipfp4nb6nsp87msx9v5n8l5mir15qcy4-python3.12-pyngrok-7.1.6/lib/python3.12/site-packages/pyngrok/ngrok.py", line 156, in get_ngrok_process
    return process.get_process(pyngrok_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ipfp4nb6nsp87msx9v5n8l5mir15qcy4-python3.12-pyngrok-7.1.6/lib/python3.12/site-packages/pyngrok/process.py", line 235, in get_process
    return _start_process(pyngrok_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ipfp4nb6nsp87msx9v5n8l5mir15qcy4-python3.12-pyngrok-7.1.6/lib/python3.12/site-packages/pyngrok/process.py", line 398, in _start_process
    raise PyngrokNgrokError(f"The ngrok process errored on start: {ngrok_process.startup_error}.",
pyngrok.exception.PyngrokNgrokError: The ngrok process errored on start: authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n.